"""add user status

Revision ID: 876f9afd2483
Revises: ed460618b91f
Create Date: 2026-08-12 17:45:44.262660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876f9afd2483'
down_revision: Union[str, Sequence[str], None] = 'ed460618b91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
