"""add user status

Revision ID: 876f9afd2483
Revises: ed460618b91f
Create Date: 2026-08-12 17:45:44.262660

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876f9afd2483'
down_revision: Union[str, Sequence[str], None] = 'ed460618b91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    userstatus_enum = postgresql.ENUM(
        'ACTIVE', 'INACTIVE', 'BANNED', 'PENDING_VERIFICATION',
        name='userstatus'
    )
    userstatus_enum.create(op.get_bind())

    op.add_column(
        'user',
        sa.Column(
            'status',
            postgresql.ENUM(
                'ACTIVE', 'INACTIVE', 'BANNED', 'PENDING_VERIFICATION',
                name='userstatus',
                create_type=False
            ),
            nullable=False,
            server_default='ACTIVE'
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
